<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Support\Facades\Redis;
use Tests\TestCase;

class TrendingTest  extends TestCase
{

    use DatabaseMigrations;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Redis::del('trending_threads');
    }


    /** @test */
    public function it_increments_the_test_score_each_time_it_is_read()
    {
        $this->assertEmpty(Redis::zrevrange('trending_threads',0,-1));

        $thread = create('App\Thread');

        $this->call('GET',$thread->path());

        $trending = Redis::zrevrange('trending_threads',0,-1);

        $this->assertCount(1 , $trending);

        $this->assertCount(1,Redis::zrevrange('trending_threads',0,-1));

        $this->assertEquals($thread->title, json_decode($trending[0])->title);
    }

}
